# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - MackenzieC-EWU-CSCD379-2021-Spring(Production), Build and deploy DotnetCore app

on:
  push:
    branches: [ Assignment* ]
  pull_request:
    branches: [ Assignment* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Get Directory
      run: pwd

    - name: Run Npm Build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: |
        npm install
        npm run build:prod

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Web
      run: dotnet build --no-restore

    - name: Test Web
      run: dotnet test --no-build --verbosity normal
      
    - name: dotnet publish
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binSecretSanta

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: MackenzieC-EWU-CSCD379-2021-Spring
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A7DC7A3708E343EBA78E226093799FC5 }}
        package: ${{env.DOTNET_ROOT}}/binSecretSanta

    - name: Verify Build Badge
      working-directory: ./
      shell: pwsh
      run: |
        [bool]$buildBadgeExists=$false
        Get-Item ./README.md | Get-Content | Where-Object { $_ -like "*badge.svg*"} | Foreach-Object { $buildBadgeExists = $true; break }
        if(-not $buildBadgeExists) {
          throw "Build Badge does not exist in README.md"
        }

